---
- name: Stop services
  command: foreman-maintain service stop

- name: Update yum
  command: yum update -y

- name: Run capsule-installer command
  command: satellite-installer --scenario capsule --upgrade 
